from enum import Enum


class Command(Enum):
    CREATE_PARKING_LOT = 2
    PARK = 3
    LEAVE = 2
    STATUS = 1
    REGISTRATION_NUMBERS_FOR_CARS_WITH_COLOUR = 2
    SLOT_NUMBERS_FOR_CARS_WITH_COLOUR = 2
    SLOT_NUMBER_FOR_REGISTRATION_NUMBER = 2
